-- Valeurs par défaut plateforme + droits accordés aux photographes
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "includedPhotos" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "allPhotosPrice" INTEGER;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "expiryDays" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "allowPricing" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "allowExpiry" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "allowAllPhotos" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "priceMin" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "priceMax" INTEGER NOT NULL DEFAULT 500;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "maxExpiryDays" INTEGER NOT NULL DEFAULT 90;
